[package]
name = "cce-text-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ui = { git = "https://github.com/lsgalante/cce-ui.git", rev = "a0e43099d1489d6b715bad5fecb48b1a5bd4728e" }
smithay-client-toolkit = "0.19.2"
calloop = "0.13.0"
calloop-wayland-source = "0.3.0"
wayland-client = { version = "0.31", features = ["system"] }
xkeysym = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
